version: '3.7'

services:
  telegram_bot_db:
    image: postgres:16.3-alpine3.19
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Seoul"
    networks:
      - backend
    ports:
      - "5432:5432"

  telegram_bot:
    image: ghcr.io/piorosen/colllection-telegram:1.0.2
    # build: 
      # context: '.'
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_API_TOKEN: ${TELEGRAM_BOT_API_TOKEN}
      TELEGRAM_BOT_API_CHAT_ID: ${TELEGRAM_BOT_API_CHAT_ID}
      POSTGRES_IP: ${POSTGRES_IP}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
